app:
  name: "web_app"
  mode: "dev"
  port: 9090
  version: "0.1"
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "shengbin"
  password: "2236141"
  database_name: "test"
  charset: utf8mb4
  max_open_conns: 200
  max_idle_conns: 200
  driver_name: "mysql"
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100